/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eneaceolini_exapp_FFTW */

#ifndef _Included_com_eneaceolini_exapp_FFTW
#define _Included_com_eneaceolini_exapp_FFTW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eneaceolini_exapp_FFTW
 * Method:    executeJNI
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_eneaceolini_fft_FFTW_executeJNI
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_eneaceolini_exapp_FFTW
 * Method:    initThreadsJNI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_eneaceolini_fft_FFTW_initThreadsJNI
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_eneaceolini_exapp_FFTW
 * Method:    areThreadsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_eneaceolini_fft_FFTW_areThreadsEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_eneaceolini_exapp_FFTW
 * Method:    removeThreadsJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eneaceolini_fft_FFTW_removeThreadsJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
