/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_eneaceolini_exapp_FFTHelper.h"
#include <math.h>
/* Header for class com_eneaceolini_exapp_FFTHelper */


JNIEXPORT void JNICALL Java_com_eneaceolini_exapp_FFTHelper_cfft
  (JNIEnv * env, jobject obj, jshort dir , jlong m, jdoubleArray x, jdoubleArray y){

}


