/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_eneaceolini_exapp_MainActivity.h"
/* Header for class com_eneaceolini_exapp_MainActivity */


JNIEXPORT jstring JNICALL Java_com_eneaceolini_exapp_MainActivity_getStringFromNative
  (JNIEnv * env, jobject obj){
  return (*env)->NewStringUTF(env,"Hello from JNI!");
}

